title: My personal blog
author: Gerald Haxhillari
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Web Developer & Designer

# social links
twitter_username: G3RA7D
github_username:  GeraldHaxhillari

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
